version: "3.3"
services:
   rethinkdb:
      image: rethinkdb:2.3.6
      ports:
         - "8080:8080"
         - "28015:28015"
   seed:
      image: seed
      build:
         context: ./test/fixture/services/seed
      restart: "no"
      depends_on:
         - rethinkdb
   repository:
      image: repository
      build:
         context: ./test/fixture/services/repository
   mvp:
      image: equate/mvp
      build:
         dockerfile: Dockerfile.js
         context: ./
      stdin_open: true
      environment:
        - "NODE_ENV=development"
      tty: true
      ports:
         - "8000:8000"
      depends_on:
         - seed
