version: "3.3"
services:
   rethinkdb:
      image: rethinkdb:2.3.6
      ports:
         - "8080:8080"
         - "28015:28015"
   seed:
      image: seed
      build:
         context: ./services/seed
      restart: "no"
      depends_on:
         - rethinkdb
   mvp:
      image: equate/mvp
      build:
         dockerfile: Dockerfile.js
         context: ./
      restart: "always"
      ports:
         - "8000:8000"
      depends_on:
         - seed
      environment:
         - "MVP_LOGGER_LEVEL=trace"
   resolver.api.domain.query.load:
      image: equate/mvp-microservice:api.domain.query.load
      build:
         context: ./services/resolvers/api/domain/query/load
      restart: "always"
   resolver.utils.get:
      image: equate/mvp-resolver:utils.get
      build:
         context: ./services/resolvers/utils/get
      restart: "always"
